-- Tenant root (ADR-0005). Every other domain table will reference it through organization_id.
-- Identifiers are generated by the application (docs/04-modelo-de-dados.md, section 1).
CREATE TABLE organization (
    id         uuid        PRIMARY KEY,
    name       text        NOT NULL,
    slug       text        NOT NULL,
    status     text        NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT organization_slug_uk UNIQUE (slug),
    CONSTRAINT organization_status_ck CHECK (status IN ('ACTIVE', 'SUSPENDED'))
);
