package com.devopsaaas.audit;

/** Audited actions. The list grows with each slice (docs/04-modelo-de-dados.md, section 4.11). */
public enum AuditAction {
    ENVIRONMENT_CREATED,
    ENVIRONMENT_UPDATED,
    ENVIRONMENT_AUTONOMY_CHANGED,
    SERVICE_ALLOWLISTED,
    SERVICE_UPDATED,
    SERVICE_DISABLED,
    SERVICE_ENABLED,
    TOOL_CALL_DENIED,
    TOOL_CALL_AWAITING_APPROVAL,
    TOOL_EXECUTION_STARTED,
    TOOL_EXECUTION_SUCCEEDED,
    TOOL_EXECUTION_FAILED,
    TOOL_EXECUTION_TIMED_OUT,
    TOOL_EXECUTION_OUTCOME_UNKNOWN
}
