package com.devopsaaas.agent;

import com.devopsaaas.agent.ExecutionJournal.Checkpoint;
import com.devopsaaas.agent.ExecutionJournal.LlmCallData;
import com.devopsaaas.agent.ExecutionJournal.RecordedLlmCall;
import com.devopsaaas.agent.ExecutionJournal.ToolSlot;
import com.devopsaaas.llm.LlmException;
import com.devopsaaas.llm.LlmFinishReason;
import com.devopsaaas.llm.LlmGateway;
import com.devopsaaas.llm.LlmRequest;
import com.devopsaaas.llm.LlmResponse;
import com.devopsaaas.llm.LlmToolCall;
import com.devopsaaas.shared.security.PermissionLookup;
import com.devopsaaas.tool.execution.ToolExecutionOutcome;
import com.devopsaaas.tool.execution.ToolExecutionRequest;
import com.devopsaaas.tool.execution.ToolExecutionStatus;
import com.devopsaaas.tool.execution.ToolExecutor;
import com.devopsaaas.tool.policy.PolicyContext;
import com.devopsaaas.tool.policy.ToolProposal;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import io.micrometer.core.instrument.MeterRegistry;
import java.time.Duration;
import java.util.List;
import java.util.Optional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 * The agent loop, controlled by the backend (ADR-0002): the model proposes, and the code decides, executes,
 * records and stops. Each turn:
 *
 * <ol>
 *   <li>checkpoint: still RUNNING? iteration and active-time budget left?</li>
 *   <li>rebuild the request from the records, with the tools the requester may use <em>now</em>;</li>
 *   <li>call the model (no transaction open) and record the call;</li>
 *   <li>for each proposal: count it against the budget first, then hand it to the tool executor and its
 *       policy chain;</li>
 *   <li>no proposal: the text is the answer.</li>
 * </ol>
 */
@Component
class AgentOrchestrator {

    private static final Logger log = LoggerFactory.getLogger(AgentOrchestrator.class);

    private final ExecutionJournal journal;
    private final LlmRequestFactory requests;
    private final LlmGateway llm;
    private final ToolExecutor tools;
    private final PermissionLookup permissions;
    private final MeterRegistry meters;

    AgentOrchestrator(ExecutionJournal journal, LlmRequestFactory requests, LlmGateway llm, ToolExecutor tools,
            PermissionLookup permissions, MeterRegistry meters) {
        this.journal = journal;
        this.requests = requests;
        this.llm = llm;
        this.tools = tools;
        this.permissions = permissions;
        this.meters = meters;
    }

    @SuppressFBWarnings(value = "CRLF_INJECTION_LOGS", justification = "Logs a UUID generated by the application")
    void run(ExecutionRef ref) {
        Optional<ExecutionState> started = journal.start(ref);
        if (started.isEmpty()) {
            return;
        }
        ExecutionState state = started.get();
        ActiveClock clock = new ActiveClock();
        try {
            loop(state, clock);
        } catch (RuntimeException exception) {
            log.error("Agent execution {} failed unexpectedly", ref.executionId(), exception);
            journal.finish(ref, AgentExecutionStatus.FAILED, "INTERNAL_ERROR");
        }
    }

    @SuppressFBWarnings(value = "CRLF_INJECTION_LOGS", justification = "Logs a UUID generated by the application")
    private void loop(ExecutionState state, ActiveClock clock) {
        ExecutionRef ref = state.ref();
        while (true) {
            if (journal.checkpoint(ref, clock.lap()) == Checkpoint.STOPPED) {
                return;
            }
            Duration remaining = Duration.ofMillis(journal.remainingActiveMs(ref));
            Optional<LlmRequest> request = requests.build(state,
                    permissions.currentPermissions(state.organizationId(), state.requestedBy()), remaining);
            if (request.isEmpty()) {
                journal.finish(ref, AgentExecutionStatus.FAILED, "ENVIRONMENT_UNAVAILABLE");
                return;
            }

            long callStart = System.nanoTime();
            LlmResponse response = null;
            LlmException failure = null;
            try {
                response = llm.complete(request.get());
            } catch (LlmException exception) {
                failure = exception;
            } catch (RuntimeException exception) {
                log.error("LLM gateway failed for execution {}", ref.executionId(), exception);
                failure = new LlmException(LlmException.Category.INVALID_RESPONSE, "Unexpected gateway failure");
            }
            int durationMs = (int) Duration.ofNanos(System.nanoTime() - callStart).toMillis();
            RecordedLlmCall recorded = journal.recordLlmCall(ref, callData(response, failure, durationMs), clock.lap());
            meterLlmCall(response, failure, durationMs);

            if (failure != null) {
                // RNF-CONF-10: a clear reason, no half-written state.
                journal.finish(ref, AgentExecutionStatus.FAILED, "LLM_" + failure.category().name());
                return;
            }
            if (!recorded.stillRunning()) {
                // Cancelled while the model was answering: the call is recorded, nothing else runs.
                return;
            }
            if (!response.toolCalls().isEmpty()) {
                if (!runProposals(state, recorded, response, clock)) {
                    return;
                }
                continue;
            }
            if (response.text() == null || response.text().isBlank()) {
                journal.finish(ref, AgentExecutionStatus.FAILED, "LLM_EMPTY_RESPONSE");
                return;
            }
            journal.complete(ref, response.text(), response.finishReason() == LlmFinishReason.LENGTH);
            return;
        }
    }

    /** Returns true when the loop should ask the model again. */
    private boolean runProposals(ExecutionState state, RecordedLlmCall recorded, LlmResponse response,
            ActiveClock clock) {
        ExecutionRef ref = state.ref();
        boolean waitingApproval = false;
        List<LlmToolCall> calls = response.toolCalls();
        for (int i = 0; i < calls.size(); i++) {
            LlmToolCall call = calls.get(i);
            // The proposal is counted BEFORE the policy evaluates it: a model producing invalid proposals
            // spends its budget like any other.
            Optional<ToolSlot> slot = journal.countToolCall(ref);
            if (slot.isEmpty()) {
                return false;
            }
            ToolExecutionOutcome outcome = tools.execute(new ToolExecutionRequest(
                    new PolicyContext(state.organizationId(), state.environmentId(), state.requestedBy(),
                            Math.max(0, slot.get().remainingToolCalls())),
                    state.id(), recorded.id(), slot.get().seq(),
                    new ToolProposal(call.name(), call.argumentsJson(), call.id(), response.text())));
            if (slot.get().overBudget()) {
                // The first proposal beyond the budget is recorded (and denied); the rest of this turn is
                // dropped instead of being written one by one.
                int dropped = calls.size() - i - 1;
                if (dropped > 0) {
                    meters.counter("devops.agent.proposals.dropped").increment(dropped);
                }
                clock.lap();
                journal.finish(ref, AgentExecutionStatus.BUDGET_EXCEEDED, "MAX_TOOL_CALLS");
                return false;
            }
            waitingApproval |= outcome.status() == ToolExecutionStatus.WAITING_APPROVAL;
        }
        if (waitingApproval) {
            // Resuming after the human decision arrives with slice 7.
            journal.waitForApproval(ref);
            return false;
        }
        return true;
    }

    private LlmCallData callData(LlmResponse response, LlmException failure, int durationMs) {
        if (failure != null) {
            return new LlmCallData(llm.model(), LlmCallOutcome.ERROR, null, 0, 0, durationMs,
                    failure.category().name());
        }
        return new LlmCallData(llm.model(), LlmCallOutcome.valueOf(response.finishReason().name()), response.text(),
                response.usage().inputTokens(), response.usage().outputTokens(), durationMs, null);
    }

    private void meterLlmCall(LlmResponse response, LlmException failure, int durationMs) {
        String outcome = failure != null ? failure.category().name() : response.finishReason().name();
        meters.timer("devops.llm.calls", "provider", llm.provider(), "outcome", outcome)
                .record(Duration.ofMillis(durationMs));
        if (response != null) {
            meters.counter("devops.llm.tokens", "provider", llm.provider(), "direction", "input")
                    .increment(response.usage().inputTokens());
            meters.counter("devops.llm.tokens", "provider", llm.provider(), "direction", "output")
                    .increment(response.usage().outputTokens());
        }
    }

    /** Processing time only (RF-26): a paused execution waiting for approval does not tick. */
    private static final class ActiveClock {

        private long mark = System.nanoTime();

        long lap() {
            long now = System.nanoTime();
            long elapsed = Duration.ofNanos(now - mark).toMillis();
            mark = now;
            return elapsed;
        }
    }
}
