package com.devopsaaas.agent;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import io.micrometer.core.instrument.Gauge;
import io.micrometer.core.instrument.MeterRegistry;
import jakarta.annotation.PreDestroy;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Semaphore;
import java.util.function.Consumer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 * In-process dispatcher (docs/03-arquitetura.md, section 8): at most {@code workers} executions run at once,
 * and at most {@code queueCapacity} more wait. The state lives in PostgreSQL, not here; replacing this with a
 * broker later means one new implementation of the same role.
 *
 * <p>A slot is reserved <em>before</em> an execution is written, so a full queue is refused with 503 instead
 * of leaving an accepted execution that nothing will run.
 */
@Component
class ExecutionDispatcher {

    private static final Logger log = LoggerFactory.getLogger(ExecutionDispatcher.class);

    /** A place in the queue, released when the execution ends or when it was never created. */
    final class Reservation {

        private boolean released;

        synchronized void release() {
            if (!released) {
                released = true;
                capacity.release();
            }
        }
    }

    private final AgentOrchestrator orchestrator;
    private final Semaphore capacity;
    private final Semaphore running;
    private final ExecutorService threads = Executors.newVirtualThreadPerTaskExecutor();

    ExecutionDispatcher(AgentOrchestrator orchestrator, AgentProperties properties, MeterRegistry meters) {
        this.orchestrator = orchestrator;
        this.capacity = new Semaphore(properties.workers() + properties.queueCapacity(), true);
        this.running = new Semaphore(properties.workers(), true);
        Gauge.builder("devops.agent.dispatch.available", capacity, Semaphore::availablePermits)
                .description("Executions that can still be accepted").register(meters);
    }

    Optional<Reservation> tryReserve() {
        return capacity.tryAcquire() ? Optional.of(new Reservation()) : Optional.empty();
    }

    void dispatch(Reservation reservation, ExecutionRef ref) {
        threads.execute(() -> runReserved(reservation, ref, orchestrator::run));
    }

    /**
     * Slice 7: resumes an execution whose approvals were decided. Best effort: with the queue full it does
     * nothing, and the approval sweep tries again from the state in the database. Resuming twice is harmless.
     */
    boolean resume(ExecutionRef ref) {
        Optional<Reservation> reservation = tryReserve();
        reservation.ifPresent(reserved -> threads.execute(() -> runReserved(reserved, ref, orchestrator::resume)));
        return reservation.isPresent();
    }

    @SuppressFBWarnings(value = "CRLF_INJECTION_LOGS", justification = "Logs a UUID generated by the application")
    private void runReserved(Reservation reservation, ExecutionRef ref, Consumer<ExecutionRef> work) {
        try {
            running.acquire();
            try {
                work.accept(ref);
            } finally {
                running.release();
            }
        } catch (InterruptedException exception) {
            Thread.currentThread().interrupt();
        } catch (RuntimeException exception) {
            log.error("Dispatch of execution {} failed", ref.executionId(), exception);
        } finally {
            reservation.release();
        }
    }

    /** Startup: re-dispatch executions that were accepted but never started, waiting for room if needed. */
    void redispatch(List<ExecutionRef> queued) {
        if (queued.isEmpty()) {
            return;
        }
        threads.execute(() -> {
            for (ExecutionRef ref : queued) {
                try {
                    capacity.acquire();
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    return;
                }
                dispatch(new Reservation(), ref);
            }
        });
    }

    @PreDestroy
    void shutdown() {
        threads.shutdownNow();
    }
}
